exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("phoenixEvent")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("phoenixEvent").insert([
        {
        event_id: 1,
          summary: "Wine And Beer Aficionados",
          location: "Denver, Colorado",
          description: "Wine and Beer Tasting with a Live Band",
          start_time: "6:00pm",
          start_date: "May 2 2020",
          end_time: "10:00pm",
          end_date: "May 2 2020",
        },

        {
          event_id: 2,
          summary: "Marathon And New Runner Enthusiasts",
          location: "Los Angeles, California",
          description:
            "Come Meet like minded Runners and Enjoy New Products and Equipment",
          start_time: "11:00am",
          start_date: "May 3 2020",
          end_time: "3:00pm",
          end_date: "May 3 2020",
        },

        {
          event_id: 3,
          summary: "Movie Premier Night",
          location: "Hollywood, California",
          description:
            "Meet New Friends while you sign up for the latest Movie Premiers",
          start_time: "6:00pm",
          start_date: "May 6 2020",
          end_time: "10:00pm",
          end_date: "May 6 2020",
        },

        {
          event_id: 4,
          summary: "Bird Watching Buddies",
          location: "Boiler Bay, Oregon ",
          description:
            "Meet New Bird Watching Buddies and see the latest equipment  & discover best new hotspots",
          start_time: "11:00am",
          start_date: "May 9 2020",
          end_time: "3:00pm",
          end_date: "May 9 2020",
        },

        {
          event_id: 5,
          summary: "Park Exploration Night",
          location: "Austin, Texas",
          description:
            "Meet new friends & explore park information and discounts",
          start_time: "6:00pm",
          start_date: "May 10 2020",
          end_time: "10:00pm",
          end_date: "May 10 2020",
        },

        {
          event_id: 6,
          summary: "Museum Exploration Afternoon",
          location: "Boston, Massachusetts",
          description: "Meet new friends & explore museums virtually",
          start_time: "11:00am",
          start_date: "May 13 2020",
          end_time: "3:00pm",
          end_date: "May 13 2020",
        },

        {
          event_id: 7,
          summary: "Yoga And Meditation Morning",
          location: "San Francisco, California",
          description:
            "Meet new friends, sample different yogas and types of meditations",
          start_time: "10:00am",
          start_date: "May 16 2020",
          end_time: "2:00pm",
          end_date: "May 16 2020",
        },

        {
          event_id: 8,
          summary: "Hiking and Naturist Enthusiasts",
          location: "Seattle, Washiington",
          description: "Meet new hiking friends, best hiking locations and times presentation",
          start_time: "11:00am",
          start_date: "May 17 2020",
          end_time: "3:00pm",
          end_date: "May 17 2020",
        },
        {
          event_id: 9,
          summary: "Art Museum Exhibit",
          location: "Los Angeles, California",
          description: "Meet new artist enthusiasts, appetizers and drinks provided",
          start_time: "6:00pm",
          start_date: "May 20 2020",
          end_time: "10:00pm",
          end_date: "May 20 2020",
        },
        {
          event_id: 10,
          summary: "Philanthropy Enthusiasts",
          location: "Sacramento, California",
          description: "Meet other charity minded friends and speak with local charities",
          start_time: "5:00pm",
          start_date: "May 23 2020",
          end_time: "9:00pm",
          end_date: "May 23 2020",
        },
        {
          event_id: 11,
          summary: "Kayaking and Paddle Boarding",
          location: "Newport Beach, California",
          description: "Join new and old friends and travel from Back Bay to the Pacific Ocean for a picnic lunch",
          start_time: "8:00am",
          start_date: "May 24 2020",
          end_time: "2:00pm",
          end_date: "May 24 2020",
        },
        {
          event_id: 12,
          summary: "Bookstores Adventure",
          location: "Midtown New York, New York",
          description: "Meet New friends on an adventure of touring the Six floors of Argosy Book Store, beverages and appetizers",
          start_time: "6:00pm",
          start_date: "May 27 2020",
          end_time: "10:00pm",
          end_date: "May 27 2020",
        },
        {
          event_id: 13,
          summary: "Guest Chef",
          location: "New York City, New York",
          description: "Pick a partner to be our guest chefs and learn the art and fun of cooking as a team",
          start_time: "6:00pm",
          start_date: "May 30 2020",
          end_time: "10:00pm",
          end_date: "May 30 2020",
        },
        {
          event_id: 14,
          summary: "The Art of Investment",
          location: "New York, New York",
          description: "Meet new friends and collaborate to make that dream getaway, vaction home, car come true ",
          start_time: "11:00am",
          start_date: "May 31 2020",
          end_time: "2:00pm",
          end_date: "May 31 2020",
        },
        {
          event_id: 15,
          summary: "Backyard BBQ/Smoking and Entertaining",
          location: "Salt Lake City, Utah",
          description: "Meet new friends, see new BBQ's, Taste New Flavors, Inspired Backyard Party Themes",
          start_time: "6:00pm",
          start_date: "June 3 2020",
          end_time: "10:00pm",
          end_date: "June 3 2020",
        },
        {
          event_id: 16,
          summary: "Experts on Grapes and Barley",
          location: "Palm Springs, California",
          description: "Wine and Beer Tasting with a Live Band",
          start_time: "6:00pm",
          start_date: "June 6 2020",
          end_time: "10:00pm",
          end_date: "June 6 2020",
        },

        {
          event_id: 17,
          summary: "Boston Marathon And New Runner Enthusiasts",
          location: "Boston, Massachusetts",
          description:
            "Come Meet like minded in the special after run party",
          start_time: "6:00am",
          start_date: "June 7 2020",
          end_time: "3:00pm",
          end_date: "June 7 2020",
        },

        {
          event_id: 18,
          summary: "Broadway Premier Night",
          location: "New York, New York",
          description:
            "Meet New Friends while you sign up for the latest Broadway Shows",
          start_time: "6:00pm",
          start_date: "June 10 2020",
          end_time: "10:00pm",
          end_date: "June 10 2020",
        },

        {
          event_id: 19,
          summary: "Birds of Arizona",
          location: "Cave Creek Canyon, Arizona ",
          description:
            "Meet New Bird Watching Buddies and see the latest equipment  & enjoy an Arizona Sunrise breakfast",
          start_time: "5:00am",
          start_date: "June 13 2020",
          end_time: "10:00am",
          end_date: "June 13 2020",
        },

        {
          event_id: 20,
          summary: "Park Exploration Night",
          location: "Orlando, Florida",
          description:
            "Meet new friends & pick a park information and discounts will be offered for prepurchase",
          start_time: "11:00am",
          start_date: "June 14 2020",
          end_time: "3:00pm",
          end_date: "June 14 2020",
        },

        {
          event_id: 21,
          summary: "Museum Exploration Afternoon",
          location: "Washington D. C. ",
          description: "Meet new friends & pick a museum to visit, end the night with a cocktail party",
          start_time: "5:00pm",
          start_date: "June 17 2020",
          end_time: "10:00pm",
          end_date: "June 17 2020",
        },

        {
          event_id: 22,
          summary: "Seattle HotSpot Yoga And Meditation Morning",
          location: "Golden Gardens, Washington",
          description:
            "Meet new friends, sample different yogas and types of meditations",
          start_time: "8:00am",
          start_date: "June 20 2020",
          end_time: "12:00pm",
          end_date: "June 20 2020",
        },

        {
          event_id: 23,
          summary: "Muir Woods Hiking and Naturist ",
          location: "San Francisco, California",
          description: "Meet new hiking friends, hike in awe of ancient Redwood trees",
          start_time: "9:00am",
          start_date: "June 21 2020",
          end_time: "3:00pm",
          end_date: "June 21 2020",
        },
        {
          event_id: 24,
          summary: "MET Art Museum Exhibit",
          location: "New York City, New York",
          description: "Meet new art and history enthusiasts, appetizers and drinks provided",
          start_time: "6:00pm",
          start_date: "June 24 2020",
          end_time: "10:00pm",
          end_date: "June 24 2020",
        },
        {
          event_id: 25,
          summary: "Philanthropy Enthusiasts",
          location: "Houston, Texas",
          description: "Meet other passionate charity minded friends and speak with local charities, team up for a cause",
          start_time: "2:00pm",
          start_date: "June 27 2020",
          end_time: "5:00pm",
          end_date: "June 27 2020",
        },
        {
          event_id: 26,
          summary: "Kayaking and Paddle Boarding",
          location: "St. Augustine, Florida",
          description: "Join new and old friends and travel the nations oldest coastal city, ending on the Atlantic Ocean for a picnic lunch",
          start_time: "8:00am",
          start_date: "June 28 2020",
          end_time: "2:00pm",
          end_date: "June 28 2020",
        },
        {
          event_id: 27,
          summary: "Bookstores Adventure",
          location: "Los Angeles, California",
          description: "Meet New friends on an adventure of touring The Last  Book Store, beverages and appetizers",
          start_time: "6:00pm",
          start_date: "July 1 2020",
          end_time: "10:00pm",
          end_date: "July 1 2020",
        },
        {
          event_id: 28,
          summary: "Guest Chef",
          location: "Austin, Texas",
          description: "Pick a partner to be our guest chefs and learn the art and fun of cooking as a team, cook your own lunch",
          start_time: "10:00am",
          start_date: "July 5 2020",
          end_time: "2:00pm",
          end_date: "July 5 2020",
        },
        {
          event_id: 29,
          summary: "The Art of Investment",
          location: "Silicon Valley, California",
          description: "Meet new friends and collaborate to make that dream getaway, vaction home, car come true ",
          start_time: "11:00am",
          start_date: "July 8 2020",
          end_time: "2:00pm",
          end_date: "July 8 2020",
        },
        {
          event_id: 30,
          summary: "Backyard BBQ/Smoking and Entertaining",
          location: "Houston, Texas",
          description: "Meet new friends, see new BBQ's, Taste New Flavors, Inspired Backyard Party Themes",
          start_time: "6:00pm",
          start_date: "July 11 2020",
          end_time: "10:00pm",
          end_date: "July 11 2020",
        },
      ]);
    });
};
